### ISSUE TITLE
Tried to deploy and it spun for hours doing nothing

### ISSUE THREAD

**Issue by burgebj** [stratisproject/ICO-Platform#2]
I tried using the deploy link and it spun for hours and did nothing, seems it is not working.

**Comment by StratisIain** [comment]
Hi @burgebj 

We have seen this happening, however, it all instances I've seen the deployment is still successful. Please check to see if the resources were correctly provisioned to the resource group.

Whilst in the resource group, you can select "Deployment" from the left pane and ensure that the status is "Success"

**Comment by burgebj** [comment]
i hit the deploy but it just sits there and spins

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

R/S,

Brandon Burge

**Comment by StratisIain** [comment]
@burgebj 

Do you get ot the point where you define the Site Name, Resource Group Name, SQL Database Password etc?

**Comment by burgebj** [comment]
The issue is you must first have your account setup in azure correctly,
then it will work

R/S,

Brandon Burge

**Comment by StratisIain** [comment]
Ah yes, you must have an active Azure Subscription assoicated with the specfified account and have the respective rights to deploy in order to complete the deployment.

**Comment by burgebj** [comment]
I finally did but it doesn't follow the documentation there is no stratis
group for directory  no pay as you go... few things missing.

R/S,

Brandon Burge

**Comment by burgebj** [comment]
R/S,

Brandon Burge

**Comment by StratisIain** [comment]
The documentation assumes that you already have an active Azure subscription associated with your account.

The name of the subscription can vary depnedant on the name ofcourse.

**Comment by burgebj** [comment]
only choice is default directory?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

R/S,

Brandon Burge
