### ISSUE TITLE
Source code of web deployment package

### ISSUE THREAD

**Issue by armujahid** [stratisproject/ICO-Platform#5]
`azuredeploy.json` is pointing to a web deployment package. Current package URI is https://stratisstorage.blob.core.windows.net/ico/Release/1.0.0/Stratis.ICOPlatform.zip?st=2018-05-08T23%3A00%3A00Z&se=2018-12-31T21%3A59%3A00Z&sp=r&sv=2017-07-29&sr=b&sig=A8X%2FmweIAVjKb537w%2FxLHlgloGHVC42SF4hwjf1jl%2Fg%3D

Its pre compiled .NET Core app. I want to ask will stratis release its source code?

**Comment by YakupIpek** [comment]
@armujahid This is not planned yet.

**Comment by StratisIain** [comment]
At present only Onfido is supported as a KYC Vendor.

https://onfido.com

Additional vendors will be added in due course, however, there are no immediate plans.
